/**
 * Model Name	: mostication.pla.model
 * Copyright by	: Mostication Inc. and Most Vending Co.,Ltd.
 * Author		: Anuntachai P.
 * Created Date	: 13/03/2014
 * Description	: singleton of all model
 */


/*
 * Using
 * 
 * Import this module in your node.js file:
 * var model = require("[ROOT]/models");		//	refer to package path
 * 
 * Get a model (set of instances)
 * var User = model.User;						//	get User model
 * User.findAll({where: [WHERE]}).success(function(users))		//	search users
 * 
 * Get singleton of sequelize object (If there is no sequelize instance, sequelize instance will generated by automatically)
 * var sequelize = model.sequelize;
 * 
 * Get Sequelize class (for using data types, utilities or other)
 * var Sequelize = model.Sequelize;
 * 
 */

//	#TODO: should not permit create, drop for db user in the production because database may be dropped from a junk code.

/*
 * ---------------------------
 * Imports
 * ---------------------------
 */

//	get configurations
var placonfig = require("../placonfig.js");

//	get logging
var mostlogModule = require("../assets/libs/mostication/nodejs/mostlog.js");
var mostlog = mostication.nodejs.mostlog;

/*
 * ---------------------------
 * Define Namespace
 * ---------------------------
 */

if(typeof(mostication)=="undefined") mostication={};
if(typeof(mostication.pla)=="undefined") mostication.pla={};
if(typeof(mostication.pla.model)=="undefined") mostication.pla.model={};

/*
 * ---------------------------
 * Global Setting
 * ---------------------------
 */	

//reference path from this file to parent directory of model files
var referToModelsPath = "./";

/*
 * ---------------------------
 * Initialize
 * ---------------------------
 */

//	if there is no sequelize, prepare models. 
//	else, use the initialized sequelize.
if(typeof(mostication.pla.model.sequelize)=="undefined") {
	
	//	get sequelize module
	var Sequelize = require("sequelize");
	
	//	set Sequelize module to model set
	mostication.pla.model.Sequelize = Sequelize;
	
	//	connect to database and create sequelize instance
	mostication.pla.model.sequelize = new Sequelize(placonfig.db.databaseName, placonfig.db.username, placonfig.db.password, {
											host: placonfig.db.host,
											port: placonfig.db.port,
											dialect: placonfig.db.dbms,
											logging: false,
											omitNull: true
											});

	//	models for loading
	var modelsList = [ "User",
	               ];
	
	//	load all models
	modelsList.forEach(function(model){
		//	load each model and set to models
		mostication.pla.model[model] = mostication.pla.model.sequelize.import(referToModelsPath + model);
	});
	
	
	//make relations
	//mostication.pla.model.[MODEL_A].belongsTo(mostication.pla.model.[MODEL_B]);
	//mostication.pla.model.[MODEL_C].hasMany(mostication.pla.model.[MODEL_D]);
	
	
}

//	export all models, relations, sequelize instance, Sequelize class
module.exports = mostication.pla.model;



/*
 * ---------------------------
 * Testing
 * ---------------------------
 */


